2020-07-16 15:34:27  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 15:34:27  [ main:75 ] - [ ERROR ]  {dataSource-1} init error
java.sql.SQLException: com.mysql.jdbc.Driver
	at com.alibaba.druid.wall.WallDenyStat$JdbcUtils.createDriver(WallDenyStat.java:677)
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1201)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:876)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.github.test.wisezone.utils.DataSourceUtil.getConnection(DataSourceUtil.java:78)
	at com.github.test.wisezone.utils.DataSourceUtil.queryList(DataSourceUtil.java:137)
	at com.github.test.wisezone.mysql.dao.impl.ExamStudentDaoImpl.queryAll(ExamStudentDaoImpl.java:50)
	at com.github.test.wisezone.mysql.biz.impl.ExamStudentBizImpl.queryAll(ExamStudentBizImpl.java:33)
	at com.github.test.wisezone.mysql.test.Test.queryAll(Test.java:32)
	at com.github.test.wisezone.mysql.test.Test.main(Test.java:49)
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.druid.wall.WallDenyStat$JdbcUtils.createDriver(WallDenyStat.java:675)
	... 10 more
2020-07-16 15:34:27  [ main:81 ] - [ ERROR ]  com.mysql.jdbc.Driver
2020-07-16 15:35:53  [ main:1 ] - [ WARN ]  -----WARN-----
2020-07-16 15:35:53  [ main:1 ] - [ ERROR ]  -----ERROR-----
2020-07-16 15:36:28  [ main:0 ] - [ ERROR ]  {dataSource-1} init error
java.sql.SQLException: url not set
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1199)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:876)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:98)
	at com.github.test.wisezone.Test.main(Test.java:25)
2020-07-16 15:45:59  [ main:0 ] - [ ERROR ]  {dataSource-1} init error
java.sql.SQLException: url not set
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1199)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:876)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:98)
	at com.github.test.wisezone.Test.main(Test.java:25)
2020-07-16 15:47:10  [ main:1 ] - [ ERROR ]  {dataSource-1} init error
java.sql.SQLException: url not set
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1199)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:876)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:98)
	at com.github.test.wisezone.Test.main(Test.java:25)
2020-07-16 15:48:21  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 15:48:21  [ main:50 ] - [ ERROR ]  {dataSource-1} init error
java.sql.SQLException: com.mysql.jdbc.Driver
	at com.alibaba.druid.wall.WallDenyStat$JdbcUtils.createDriver(WallDenyStat.java:677)
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1201)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:876)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.github.test.wisezone.utils.DataSourceUtil.getConnection(DataSourceUtil.java:78)
	at com.github.test.wisezone.utils.DataSourceUtil.queryList(DataSourceUtil.java:137)
	at com.github.test.wisezone.mysql.dao.impl.ExamStudentDaoImpl.queryAll(ExamStudentDaoImpl.java:50)
	at com.github.test.wisezone.mysql.biz.impl.ExamStudentBizImpl.queryAll(ExamStudentBizImpl.java:33)
	at com.github.test.wisezone.mysql.test.Test.queryAll(Test.java:32)
	at com.github.test.wisezone.mysql.test.Test.main(Test.java:49)
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.druid.wall.WallDenyStat$JdbcUtils.createDriver(WallDenyStat.java:675)
	... 10 more
2020-07-16 15:48:21  [ main:54 ] - [ ERROR ]  com.mysql.jdbc.Driver
2020-07-16 15:50:59  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 15:51:01  [ main:1609 ] - [ ERROR ]  init datasource error, url: jdbc:mysql://172.16.16.75:3306/exercise?characterEncoding=UTF8
java.sql.SQLException: Access denied for user 'root'@'192.168.32.38' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1215)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2255)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1642)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1708)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:912)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.github.test.wisezone.utils.DataSourceUtil.getConnection(DataSourceUtil.java:78)
	at com.github.test.wisezone.utils.DataSourceUtil.queryList(DataSourceUtil.java:137)
	at com.github.test.wisezone.mysql.dao.impl.ExamStudentDaoImpl.queryAll(ExamStudentDaoImpl.java:50)
	at com.github.test.wisezone.mysql.biz.impl.ExamStudentBizImpl.queryAll(ExamStudentBizImpl.java:33)
	at com.github.test.wisezone.mysql.test.Test.queryAll(Test.java:32)
	at com.github.test.wisezone.mysql.test.Test.main(Test.java:49)
2020-07-16 15:51:01  [ main:1615 ] - [ ERROR ]  {dataSource-1} init error
java.sql.SQLException: Access denied for user 'root'@'192.168.32.38' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1215)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2255)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1642)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1708)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:912)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.github.test.wisezone.utils.DataSourceUtil.getConnection(DataSourceUtil.java:78)
	at com.github.test.wisezone.utils.DataSourceUtil.queryList(DataSourceUtil.java:137)
	at com.github.test.wisezone.mysql.dao.impl.ExamStudentDaoImpl.queryAll(ExamStudentDaoImpl.java:50)
	at com.github.test.wisezone.mysql.biz.impl.ExamStudentBizImpl.queryAll(ExamStudentBizImpl.java:33)
	at com.github.test.wisezone.mysql.test.Test.queryAll(Test.java:32)
	at com.github.test.wisezone.mysql.test.Test.main(Test.java:49)
2020-07-16 15:51:01  [ main:1616 ] - [ ERROR ]  Access denied for user 'root'@'192.168.32.38' (using password: YES)
2020-07-16 15:55:00  [ main:0 ] - [ ERROR ]  {dataSource-1} init error
java.sql.SQLException: url not set
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1199)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:876)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:98)
	at com.github.test.wisezone.Test.main(Test.java:25)
2020-07-16 15:55:11  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 15:55:57  [ main:0 ] - [ ERROR ]  {dataSource-1} init error
java.sql.SQLException: url not set
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1199)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:876)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:98)
	at com.github.test.wisezone.Test.main(Test.java:25)
2020-07-16 16:00:10  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:10:38  [ main:2 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:12:52  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:13:15  [ main:2 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:13:33  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:13:53  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:14:29  [ main:2 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:14:50  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:15:21  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:16:05  [ main:2 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:16:28  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:18:43  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:19:58  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:22:42  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:23:24  [ main:1 ] - [ ERROR ]  初始化数据源成功
2020-07-16 16:26:35  [ main:0 ] - [ ERROR ]  {dataSource-1} init error
java.sql.SQLException: url not set
	at com.alibaba.druid.pool.DruidDataSource.resolveDriver(DruidDataSource.java:1199)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:876)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1378)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1374)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:98)
	at com.github.test.wisezone.Test.main(Test.java:25)
2020-07-16 16:26:56  [ main:1 ] - [ ERROR ]  初始化数据源成功
